/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import javax.swing.JOptionPane;

/**
 * 
 */
public class module_2 extends javax.swing.JFrame {

    /**
     * Creates new form module_2
     */
    public module_2() {
        initComponents();
        
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adul = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ac = new javax.swing.JComboBox();
        kids = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rms = new javax.swing.JComboBox();
        rm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        book = new javax.swing.JTextField();
        non = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Venkatesh\\Downloads\\bg 4.jpg")); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Venkatesh\\Downloads\\bg 3.jpg")); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Venkatesh\\Downloads\\room.jpg")); // NOI18N
        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ROOM BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 40, 220, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BOOK YOUR ROOMS!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 220, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TYPE OF ROOMS:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 100, 130, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CAPACITY:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 180, 110, 20);

        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        getContentPane().add(fn);
        fn.setBounds(280, 170, 240, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NO. OG BOOKINGS:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 330, 160, 17);
        getContentPane().add(adul);
        adul.setBounds(280, 210, 242, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NUMBER OF KIDS:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 260, 160, 17);

        ac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A/C", "NON A/C" }));
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(200, 130, 68, 20);

        kids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidsActionPerformed(evt);
            }
        });
        getContentPane().add(kids);
        kids.setBounds(280, 250, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("NUMBER OF ADULTS:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 220, 190, 20);

        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });
        getContentPane().add(cd);
        cd.setBounds(280, 290, 280, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 410, 160, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("GO BACK");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(494, 30, 110, 17);

        rms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DULEX ROOM  ", "TWIN ROOM", "QUAD  ROOM", "SUITE ROOM", " " }));
        rms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmsActionPerformed(evt);
            }
        });
        getContentPane().add(rms);
        rms.setBounds(240, 100, 130, 20);

        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        getContentPane().add(rm);
        rm.setBounds(390, 100, 150, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("NUMBER OF NIGHTS IN HOTEL: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 290, 270, 17);

        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book);
        book.setBounds(280, 330, 260, 30);
        getContentPane().add(non);
        non.setBounds(310, 130, 160, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Venkatesh\\Downloads\\20.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 750, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       String fname=fn.getText();
       String cname=book.getText();
        
        String ad=adul.getText();
       String kd=kids.getText();
        
        String night=cd.getText();
       
        
        
        
        non.setText(ac.getSelectedItem().toString());
        
        rm.setText(rms.getSelectedItem().toString());
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"capacity:"+fname+"\nbookings:"+cname+"\nno.adult:"+ad+"\nno.kids:"+kd+"no.of night:"+night+"\n\ndata has been submitted");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    menupage obj=new menupage();
    obj.setVisible(true);
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void rmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmsActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookActionPerformed

    private void kidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(module_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(module_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(module_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(module_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new module_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ac;
    private javax.swing.JTextField adul;
    private javax.swing.JTextField book;
    private javax.swing.JTextField cd;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kids;
    private javax.swing.JTextField non;
    private javax.swing.JTextField rm;
    private javax.swing.JComboBox rms;
    // End of variables declaration//GEN-END:variables
}
